### PR TITLE
remove purple hyperlink when visited

### PR DESCRIPTION
**Pull request by netbun**

### CODE REVIEW

**Comment by jayrox** [comment]
why would you remove the purple and make the color blue? this matches the color of unvisited links and goes against accessibility and good ui/ux principals.

choose a better color and i'll accept the pr

**Comment by netbun** [comment]
@jayrox for example, [https://github.com/9uuso/vertigo/](this link) remains blue even if visited

**Comment by 9uuso** [comment]
I personally think that CSS rules is out of scope of the base project -- keep the default theme clean and make it easier for the user to change the rules.

Ultimately some sort of default theme could be endorsed, but that would be in a separate repository or in a git submodule.

**Comment by jayrox** [comment]
@netbun that may be github's preference but i agree with @9uuso i believe this request it out of the scope of this project.

**Comment by netbun** [comment]
@jayrox @9usso what about implementing a theme selector such as ghost for custom themes?

**Comment by 9uuso** [comment]
Might be a possibility in future, but currently it should be easy enough to just override the current template files.

I'd imagine that anyone interested in Vertigo would be interested in it because of its technical stack. Therefore I think it is safe to assume that the user is able to override files by their own, making a theme selector kind of pointless.

**Comment by netbun** [comment]
@9uuso understandable, :+1:

**Comment by jayrox** [comment]
that being said, i wouldnt mind looking into implementing ghost themes at
some time in the future

**Pull request closed without merging**
